services:
  viewer:
    build:
      context: .
      dockerfile: docker/viewer/Dockerfile
    container_name: nook-viewer
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./output/default:/app/output/default
      - ./output/camera:/app/output/camera
    restart: unless-stopped
    networks:
      - nook

  collector:
    build:
      context: .
      dockerfile: docker/collector/Dockerfile
    container_name: nook-collector
    env_file:
      - .env
    volumes:
      - ./output/default:/app/output
    environment:
      - NOOK_TYPE=default
    restart: unless-stopped
    networks:
      - nook

  camera-collector:
    build:
      context: .
      dockerfile: docker/collector/Dockerfile
    container_name: nook-camera-collector
    env_file:
      - .env
    volumes:
      - ./output/camera:/app/output
    environment:
      - NOOK_TYPE=camera
    restart: unless-stopped
    networks:
      - nook

networks:
  nook:
    name: nook
    driver: bridge