[[subreddits]]
name = "photography"

[[subreddits]]
name = "cameras"

[[subreddits]]
name = "SonyAlpha"

[[subreddits]]
name = "CanonEOS"

[[subreddits]]
name = "Nikon"

[[subreddits]]
name = "nikon_Zseries"